# Generated by Django 4.2.9 on 2025-10-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('export_job_idx', models.AutoField(db_column='export_job_idx', primary_key=True, serialize=False)),
                ('job_type', models.TextField(choices=[('pdf', 'PDF'), ('ics', 'ICS'), ('csv', 'CSV')])),
                ('status', models.TextField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued')),
                ('storage_uri', models.TextField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trip_idx', models.ForeignKey(db_column='trip_idx', on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='plans.tripplan')),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'db_table': 'export_jobs',
            },
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(('job_type__in', ['pdf', 'ics', 'csv'])), name='export_jobs_job_type_check'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['queued', 'processing', 'done', 'failed'])), name='export_jobs_status_check'),
        ),
    ]
