# Generated by Django 4.2.9 on 2025-11-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldTime',
            fields=[
                ('world_time_idx', models.AutoField(db_column='world_time_idx', primary_key=True, serialize=False)),
                ('continent', models.CharField(max_length=50)),
                ('city_time', models.CharField(max_length=50)),
                ('time_difference', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world_times', to='common.country', to_field='country_code')),
                ('province_idx', models.ForeignKey(blank=True, db_column='province_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world_times', to='common.province')),
            ],
            options={
                'verbose_name': 'World Time',
                'verbose_name_plural': 'World Times',
                'db_table': 'world_time',
            },
        ),
    ]
