# Generated by Django 4.2.9 on 2025-11-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_idx', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='행정구역 코드', max_length=20)),
                ('name', models.CharField(help_text='행정구역명 (현지어)', max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, help_text='영문명', max_length=100, null=True)),
                ('short_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('grid_x', models.IntegerField(blank=True, help_text='격자 X', null=True)),
                ('grid_y', models.IntegerField(blank=True, help_text='격자 Y', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('level', models.IntegerField(default=2, help_text='행정구역 레벨')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'common_city',
                'ordering': ['province', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_idx', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.IntegerField(unique=True)),
                ('iso2', models.CharField(max_length=2)),
                ('country_name', models.TextField()),
                ('name_local', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'common_country',
            },
        ),
        migrations.CreateModel(
            name='Region1',
            fields=[
                ('region1_idx', models.AutoField(primary_key=True, serialize=False)),
                ('city_code', models.IntegerField(unique=True)),
                ('city_name', models.TextField()),
                ('country_code', models.ForeignKey(db_column='country_code', on_delete=django.db.models.deletion.CASCADE, to='common.country')),
            ],
            options={
                'verbose_name': 'Region 1 (City)',
                'verbose_name_plural': 'Region 1 (Cities)',
                'db_table': 'common_region1',
                'unique_together': {('country_code', 'city_code')},
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_idx', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='행정구역 코드 (국가별 상이)', max_length=20)),
                ('name', models.CharField(help_text='행정구역명 (현지어)', max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, help_text='영문명', max_length=100, null=True)),
                ('short_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('grid_x', models.IntegerField(blank=True, help_text='격자 X (국가 기상청 기준)', null=True)),
                ('grid_y', models.IntegerField(blank=True, help_text='격자 Y (국가 기상청 기준)', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('level', models.IntegerField(default=1, help_text='행정구역 레벨')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(db_column='country_idx', help_text='국가', on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='common.country')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'db_table': 'common_province',
                'ordering': ['country', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PlacesCategory',
            fields=[
                ('category_idx', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(unique=True)),
                ('text_code', models.TextField(unique=True)),
                ('name_ko', models.TextField()),
                ('name_en', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_idx', models.ForeignKey(blank=True, db_column='parent_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.placescategory')),
            ],
            options={
                'verbose_name': 'Place Category',
                'verbose_name_plural': 'Place Categories',
                'db_table': 'common_places_category',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_idx', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='행정구역 코드', max_length=20)),
                ('name', models.CharField(help_text='행정구역명 (현지어)', max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, help_text='영문명', max_length=100, null=True)),
                ('short_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('grid_x', models.IntegerField(blank=True, help_text='격자 X', null=True)),
                ('grid_y', models.IntegerField(blank=True, help_text='격자 Y', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('level', models.IntegerField(default=3, help_text='행정구역 레벨')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(db_column='city_idx', help_text='상위 행정구역', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='common.city')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'common_district',
                'ordering': ['city', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CountryElectric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
                ('hz', models.CharField(blank=True, max_length=10, null=True)),
                ('voltage', models.CharField(blank=True, max_length=20, null=True)),
                ('plug_type', models.CharField(blank=True, max_length=50, null=True)),
                ('plug_image', models.CharField(blank=True, max_length=255, null=True)),
                ('use_yn', models.CharField(default='N', max_length=1)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country', to_field='country_code')),
            ],
            options={
                'verbose_name': 'Country Electric Info',
                'verbose_name_plural': 'Country Electric Info',
                'db_table': 'country_electric',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(db_column='province_idx', help_text='상위 행정구역', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='common.province'),
        ),
        migrations.CreateModel(
            name='Region2',
            fields=[
                ('region2_idx', models.AutoField(primary_key=True, serialize=False)),
                ('region2_code', models.IntegerField()),
                ('region2_name', models.TextField()),
                ('region1_idx', models.ForeignKey(db_column='region1_idx', on_delete=django.db.models.deletion.CASCADE, to='common.region1')),
            ],
            options={
                'verbose_name': 'Region 2 (District)',
                'verbose_name_plural': 'Region 2 (Districts)',
                'db_table': 'common_region2',
                'unique_together': {('region1_idx', 'region2_code')},
            },
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['country', 'code'], name='common_prov_country_d96dff_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['country', 'name'], name='common_prov_country_c62074_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('country', 'code')},
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['city', 'code'], name='common_dist_city_id_3db0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['city', 'name'], name='common_dist_city_id_09864a_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['grid_x', 'grid_y'], name='common_dist_grid_x_cba67c_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['city', 'grid_x', 'grid_y'], name='common_dist_city_id_04bd4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('city', 'code')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province', 'code'], name='common_city_provinc_1557ce_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province', 'name'], name='common_city_provinc_3fd53e_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['grid_x', 'grid_y'], name='common_city_grid_x_f9d890_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'code')},
        ),
    ]
