# Generated by Django 4.2.9 on 2025-10-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_idx', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.IntegerField(unique=True)),
                ('iso2', models.CharField(max_length=2)),
                ('country_name', models.TextField()),
                ('name_local', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'common_country',
            },
        ),
        migrations.CreateModel(
            name='Region1',
            fields=[
                ('region1_idx', models.AutoField(primary_key=True, serialize=False)),
                ('city_code', models.IntegerField(unique=True)),
                ('city_name', models.TextField()),
                ('country_code', models.ForeignKey(db_column='country_code', on_delete=django.db.models.deletion.CASCADE, to='common.country')),
            ],
            options={
                'verbose_name': 'Region 1 (City)',
                'verbose_name_plural': 'Region 1 (Cities)',
                'db_table': 'common_region1',
                'unique_together': {('country_code', 'city_code')},
            },
        ),
        migrations.CreateModel(
            name='PlacesCategory',
            fields=[
                ('category_idx', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(unique=True)),
                ('text_code', models.TextField(unique=True)),
                ('name_ko', models.TextField()),
                ('name_en', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_idx', models.ForeignKey(blank=True, db_column='parent_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.placescategory')),
            ],
            options={
                'verbose_name': 'Place Category',
                'verbose_name_plural': 'Place Categories',
                'db_table': 'common_places_category',
            },
        ),
        migrations.CreateModel(
            name='Region2',
            fields=[
                ('region2_idx', models.AutoField(primary_key=True, serialize=False)),
                ('region2_code', models.IntegerField()),
                ('region2_name', models.TextField()),
                ('region1_idx', models.ForeignKey(db_column='region1_idx', on_delete=django.db.models.deletion.CASCADE, to='common.region1')),
            ],
            options={
                'verbose_name': 'Region 2 (District)',
                'verbose_name_plural': 'Region 2 (Districts)',
                'db_table': 'common_region2',
                'unique_together': {('region1_idx', 'region2_code')},
            },
        ),
    ]
