# Generated by Django 4.2.9 on 2025-10-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryElectric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
                ('hz', models.CharField(blank=True, max_length=10, null=True)),
                ('voltage', models.CharField(blank=True, max_length=20, null=True)),
                ('plug_type', models.CharField(blank=True, max_length=50, null=True)),
                ('plug_image', models.CharField(blank=True, max_length=255, null=True)),
                ('use_yn', models.CharField(default='N', max_length=1)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country', to_field='country_code')),
            ],
            options={
                'verbose_name': 'Country Electric Info',
                'verbose_name_plural': 'Country Electric Info',
                'db_table': 'country_electric',
            },
        ),
    ]
