# Generated by Django 4.2.9 on 2025-10-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_countryelectric'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAlert',
            fields=[
                ('alert_idx', models.AutoField(db_column='alert_idx', primary_key=True, serialize=False)),
                ('level', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_alerts', to='common.country', to_field='country_code')),
            ],
            options={
                'verbose_name': 'Trip Alert',
                'verbose_name_plural': 'Trip Alerts',
                'db_table': 'trip_alerts',
            },
        ),
        migrations.DeleteModel(
            name='TravelAlert',
        ),
    ]
