# Generated by Django 4.2.9 on 2025-11-09 00:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('day_idx', models.AutoField(db_column='day_idx', primary_key=True, serialize=False)),
                ('day_no', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Trip Day',
                'verbose_name_plural': 'Trip Days',
                'db_table': 'trip_days',
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('trip_idx', models.AutoField(db_column='trip_idx', primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('party_size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('budget_currency', models.TextField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('invite_code', models.CharField(blank=True, db_index=True, help_text='6-character invite code for joining trip', max_length=10, null=True, unique=True)),
                ('invite_code_expires_at', models.DateTimeField(blank=True, help_text='Expiration time for invite code', null=True)),
                ('user_satisfaction', models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], help_text='User satisfaction feedback', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_idx', models.ForeignKey(blank=True, db_column='city_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_plans', to='common.city')),
                ('country_idx', models.ForeignKey(blank=True, db_column='country_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_plans', to='common.country')),
                ('district_idx', models.ForeignKey(blank=True, db_column='district_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_plans', to='common.district')),
                ('owner_user_idx', models.ForeignKey(db_column='owner_user_idx', on_delete=django.db.models.deletion.RESTRICT, related_name='owned_trips', to=settings.AUTH_USER_MODEL)),
                ('province_idx', models.ForeignKey(blank=True, db_column='province_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_plans', to='common.province')),
            ],
            options={
                'verbose_name': 'Trip Plan',
                'verbose_name_plural': 'Trip Plans',
                'db_table': 'trip_plans',
            },
        ),
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('trip_member_idx', models.AutoField(db_column='trip_member_idx', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('commenter', 'Commenter'), ('viewer', 'Viewer')], default='editor', max_length=20)),
                ('trip_idx', models.ForeignKey(db_column='trip_idx', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='plans.tripplan')),
                ('user_idx', models.ForeignKey(db_column='user_idx', on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Member',
                'verbose_name_plural': 'Trip Members',
                'db_table': 'trip_members',
            },
        ),
        migrations.CreateModel(
            name='TripItem',
            fields=[
                ('item_idx', models.AutoField(db_column='item_idx', primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('place', 'Place'), ('meal', 'Meal'), ('activity', 'Activity'), ('transfer', 'Transfer'), ('rest', 'Rest'), ('custom', 'Custom')], max_length=20)),
                ('title', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lock_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order_in_day', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_idx', models.ForeignKey(db_column='day_idx', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.tripday')),
                ('place_idx', models.ForeignKey(blank=True, db_column='place_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_items', to='places.place')),
            ],
            options={
                'verbose_name': 'Trip Item',
                'verbose_name_plural': 'Trip Items',
                'db_table': 'trip_items',
                'ordering': ['order_in_day'],
            },
        ),
        migrations.AddField(
            model_name='tripday',
            name='trip_idx',
            field=models.ForeignKey(db_column='trip_idx', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='plans.tripplan'),
        ),
        migrations.AddConstraint(
            model_name='tripplan',
            constraint=models.CheckConstraint(check=models.Q(('party_size__isnull', True), ('party_size__gte', 1), _connector='OR'), name='trip_plans_party_size_check'),
        ),
        migrations.AddConstraint(
            model_name='tripplan',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'confirmed', 'archived'])), name='trip_plans_status_check'),
        ),
        migrations.AddConstraint(
            model_name='tripmember',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['owner', 'editor', 'commenter', 'viewer'])), name='trip_members_role_check'),
        ),
        migrations.AlterUniqueTogether(
            name='tripmember',
            unique_together={('trip_idx', 'user_idx')},
        ),
        migrations.AddConstraint(
            model_name='tripitem',
            constraint=models.CheckConstraint(check=models.Q(('item_type__in', ['place', 'meal', 'activity', 'transfer', 'rest', 'custom'])), name='trip_items_item_type_check'),
        ),
        migrations.AlterUniqueTogether(
            name='tripday',
            unique_together={('trip_idx', 'date'), ('trip_idx', 'day_no')},
        ),
    ]
