# Generated by Django 4.2.9 on 2025-11-12 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeCrawlerJob',
            fields=[
                ('job_idx', models.AutoField(db_column='job_idx', primary_key=True, serialize=False)),
                ('file_path', models.TextField(help_text='업로드된 data.txt 파일 경로')),
                ('total_urls', models.IntegerField(default=0, help_text='총 URL 개수')),
                ('processed_count', models.IntegerField(default=0, help_text='처리 완료 개수')),
                ('success_count', models.IntegerField(default=0, help_text='성공 개수')),
                ('fail_count', models.IntegerField(default=0, help_text='실패 개수')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='에러 메시지', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTube 크롤링 작업',
                'verbose_name_plural': 'YouTube 크롤링 작업 목록',
                'db_table': 'youtube_crawler_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
