# Generated by Django 4.2.9 on 2025-10-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, help_text='6-character invite code for joining trip', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='invite_code_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration time for invite code', null=True),
        ),
    ]
