# Generated by Django 4.2.9 on 2025-11-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_youtubecrawlerjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecrawlerjob',
            name='location',
            field=models.CharField(blank=True, help_text='처리 중인 지역명', max_length=200, null=True),
        ),
    ]
