# Generated by Django 4.2.9 on 2025-10-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_tripplan_invite_code_tripplan_invite_code_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='user_satisfaction',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], help_text='User satisfaction feedback', max_length=10, null=True),
        ),
    ]
