# Generated by Django 4.2.9 on 2025-10-14 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecEvent',
            fields=[
                ('rec_event_idx', models.AutoField(db_column='rec_event_idx', primary_key=True, serialize=False)),
                ('algo', models.TextField()),
                ('request_ctx', models.JSONField(blank=True, null=True)),
                ('candidates', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_idx', models.ForeignKey(blank=True, db_column='message_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rec_events', to='chat.chatmessage')),
                ('room_idx', models.ForeignKey(blank=True, db_column='room_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rec_events', to='chat.chatroom')),
                ('trip_idx', models.ForeignKey(db_column='trip_idx', on_delete=django.db.models.deletion.CASCADE, related_name='rec_events', to='plans.tripplan')),
            ],
            options={
                'verbose_name': 'Recommendation Event',
                'verbose_name_plural': 'Recommendation Events',
                'db_table': 'rec_events',
            },
        ),
        migrations.CreateModel(
            name='RecApplied',
            fields=[
                ('rec_applied_idx', models.AutoField(db_column='rec_applied_idx', primary_key=True, serialize=False)),
                ('applied_item', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, db_column='applied_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_recommendations', to=settings.AUTH_USER_MODEL)),
                ('rec_event_idx', models.ForeignKey(db_column='rec_event_idx', on_delete=django.db.models.deletion.CASCADE, related_name='applied_recommendations', to='ai.recevent')),
            ],
            options={
                'verbose_name': 'Applied Recommendation',
                'verbose_name_plural': 'Applied Recommendations',
                'db_table': 'rec_applied',
            },
        ),
    ]
