# Generated by Django 4.2.9 on 2025-11-09 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecEvent',
            fields=[
                ('rec_event_idx', models.AutoField(db_column='rec_event_idx', primary_key=True, serialize=False)),
                ('algo', models.TextField()),
                ('request_ctx', models.JSONField(blank=True, null=True)),
                ('candidates', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_idx', models.ForeignKey(blank=True, db_column='message_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rec_events', to='chat.chatmessage')),
                ('room_idx', models.ForeignKey(blank=True, db_column='room_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rec_events', to='chat.chatroom')),
                ('trip_idx', models.ForeignKey(db_column='trip_idx', on_delete=django.db.models.deletion.CASCADE, related_name='rec_events', to='plans.tripplan')),
            ],
            options={
                'verbose_name': 'Recommendation Event',
                'verbose_name_plural': 'Recommendation Events',
                'db_table': 'rec_events',
            },
        ),
        migrations.CreateModel(
            name='RecApplied',
            fields=[
                ('rec_applied_idx', models.AutoField(db_column='rec_applied_idx', primary_key=True, serialize=False)),
                ('applied_item', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, db_column='applied_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_recommendations', to=settings.AUTH_USER_MODEL)),
                ('rec_event_idx', models.ForeignKey(db_column='rec_event_idx', on_delete=django.db.models.deletion.CASCADE, related_name='applied_recommendations', to='ai.recevent')),
            ],
            options={
                'verbose_name': 'Applied Recommendation',
                'verbose_name_plural': 'Applied Recommendations',
                'db_table': 'rec_applied',
            },
        ),
        migrations.CreateModel(
            name='TripCourseEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.TextField()),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_year', models.IntegerField(blank=True, null=True)),
                ('upload_month', models.IntegerField(blank=True, null=True)),
                ('views_num', models.IntegerField(blank=True, null=True)),
                ('content_embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Stores all original data: description, ko, en, schedules, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_idx', models.ForeignKey(blank=True, db_column='city_idx', help_text='City level (시/군/구)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlogs', to='common.city')),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlogs', to='common.country', to_field='country_code')),
                ('district_idx', models.ForeignKey(blank=True, db_column='district_idx', help_text='District level (읍/면/동)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlogs', to='common.district')),
                ('province_idx', models.ForeignKey(blank=True, db_column='province_idx', help_text='Province level (시/도)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlogs', to='common.province')),
            ],
            options={
                'verbose_name': 'Trip Course Embedding',
                'verbose_name_plural': 'Trip Course Embeddings',
                'db_table': 'trip_course_embeddings',
                'indexes': [models.Index(fields=['country_code', 'province_idx'], name='trip_course_country_587119_idx'), models.Index(fields=['upload_year', 'upload_month'], name='trip_course_upload__ed19c9_idx'), models.Index(fields=['-views_num'], name='trip_course_views_n_dca493_idx')],
            },
        ),
    ]
