# Generated by Django 4.2.9 on 2025-10-17 00:55

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_countryelectric'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelVlogEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.TextField()),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_year', models.IntegerField(blank=True, null=True)),
                ('upload_month', models.IntegerField(blank=True, null=True)),
                ('views_num', models.IntegerField(blank=True, null=True)),
                ('content_embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Stores all original data: description, ko, en, schedules, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlogs', to='common.country', to_field='country_code')),
                ('region1_idx', models.ForeignKey(blank=True, db_column='region1_idx', help_text='City level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlogs', to='common.region1')),
                ('region2_idx', models.ForeignKey(blank=True, db_column='region2_idx', help_text='District level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlogs', to='common.region2')),
            ],
            options={
                'verbose_name': 'Travel Vlog Embedding',
                'verbose_name_plural': 'Travel Vlog Embeddings',
                'db_table': 'travel_vlog_embeddings',
                'indexes': [models.Index(fields=['country_code', 'region1_idx'], name='travel_vlog_country_6c59a9_idx'), models.Index(fields=['upload_year', 'upload_month'], name='travel_vlog_upload__ad76c6_idx'), models.Index(fields=['-views_num'], name='travel_vlog_views_n_606ff0_idx')],
            },
        ),
    ]
