# Generated by Django 4.2.9 on 2025-11-12 02:08

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcourseembedding',
            name='parsed_itinerary',
            field=models.JSONField(blank=True, help_text='Structured itinerary parsed by OpenAI (places, activities, order)', null=True),
        ),
        migrations.AddField(
            model_name='tripcourseembedding',
            name='raw_content',
            field=models.TextField(blank=True, help_text='YouTube video description and transcript (raw text)', null=True),
        ),
        migrations.AlterField(
            model_name='tripcourseembedding',
            name='content_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, help_text='Vector embedding of parsed itinerary for semantic search', null=True),
        ),
        migrations.AlterField(
            model_name='tripcourseembedding',
            name='metadata',
            field=models.JSONField(blank=True, help_text='[DEPRECATED] Use raw_content and parsed_itinerary instead', null=True),
        ),
    ]
