# Generated by Django 4.2.9 on 2025-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_tripcourseembedding_parsed_itinerary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripcourseembedding',
            name='country_name',
        ),
        migrations.AddField(
            model_name='tripcourseembedding',
            name='location_name',
            field=models.CharField(blank=True, help_text='지역명 (예: 서울, 제주도, 부산)', max_length=100, null=True),
        ),
    ]
