# Generated by Django 4.2.9 on 2025-11-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_idx', models.AutoField(primary_key=True, serialize=False)),
                ('place_id', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('ko_name', models.TextField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('google_maps_uri', models.TextField(blank=True, null=True)),
                ('website_uri', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('api_key_idx', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_idx', models.ForeignKey(blank=True, db_column='city_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.city')),
                ('country_idx', models.ForeignKey(blank=True, db_column='country_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.country')),
                ('district_idx', models.ForeignKey(blank=True, db_column='district_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.district')),
                ('province_idx', models.ForeignKey(blank=True, db_column='province_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.province')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'db_table': 'place_places',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_idx', models.AutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('attributions', models.TextField(blank=True, null=True)),
                ('local_path', models.TextField(blank=True, null=True)),
                ('remote_uri', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place_idx', models.ForeignKey(db_column='place_idx', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'place_photos',
            },
        ),
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('place_category_idx', models.AutoField(primary_key=True, serialize=False)),
                ('category_idx', models.ForeignKey(db_column='category_idx', on_delete=django.db.models.deletion.RESTRICT, related_name='place_categories', to='common.placescategory')),
                ('place_idx', models.ForeignKey(db_column='place_idx', on_delete=django.db.models.deletion.CASCADE, related_name='place_categories', to='places.place')),
            ],
            options={
                'verbose_name': 'Place Category',
                'verbose_name_plural': 'Place Categories',
                'db_table': 'place_place_categories',
                'indexes': [models.Index(fields=['place_idx'], name='place_place_place_i_bc6800_idx'), models.Index(fields=['category_idx'], name='place_place_categor_55bce5_idx')],
                'unique_together': {('place_idx', 'category_idx')},
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_id'], name='place_place_place_i_c3b286_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='place_place_latitud_fb225c_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['place_idx', 'is_primary'], name='place_photo_place_i_7a926a_idx'),
        ),
    ]
