# Generated by Django 4.2.9 on 2025-11-09 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_idx', models.AutoField(db_column='user_idx', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], db_column='status', default='pending', max_length=20)),
                ('tz', models.CharField(db_column='tz', default='UTC', help_text='User timezone', max_length=50)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('identity_idx', models.AutoField(db_column='identity_idx', primary_key=True, serialize=False)),
                ('provider', models.CharField(db_column='provider', help_text='OAuth provider name (e.g., google, github, facebook)', max_length=50)),
                ('provider_uid', models.CharField(db_column='provider_uid', help_text='Unique identifier from the provider', max_length=255)),
                ('user', models.ForeignKey(db_column='user_idx', on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Identity',
                'verbose_name_plural': 'User Identities',
                'db_table': 'user_identities',
                'indexes': [models.Index(fields=['user'], name='idx_identity_user'), models.Index(fields=['provider', 'provider_uid'], name='idx_identity_provider_uid')],
            },
        ),
        migrations.AddConstraint(
            model_name='useridentity',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_uid'), name='user_identities_provider_uid_key'),
        ),
        migrations.AlterUniqueTogether(
            name='useridentity',
            unique_together={('provider', 'provider_uid')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='idx_user_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='idx_user_created_at'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'active', 'suspended', 'deleted'])), name='user_users_status_check'),
        ),
    ]
