# Generated by Django 4.2.9 on 2025-11-09 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_idx', models.AutoField(db_column='room_idx', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_idx', models.ForeignKey(db_column='trip_idx', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='plans.tripplan')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'chat_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_idx', models.AutoField(db_column='message_idx', primary_key=True, serialize=False)),
                ('msg_type', models.TextField(choices=[('text', 'Text'), ('system', 'System'), ('card', 'Card'), ('recommendation', 'Recommendation')], default='text')),
                ('content', models.TextField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_idx', models.ForeignKey(db_column='room_idx', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('user_idx', models.ForeignKey(blank=True, db_column='user_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('request_idx', models.AutoField(db_column='request_idx', primary_key=True, serialize=False)),
                ('user_message', models.TextField(help_text='User input message (full text)')),
                ('agent_response', models.TextField(blank=True, help_text='Agent response (full text)', null=True)),
                ('tools_used', models.JSONField(blank=True, help_text='List of tools used by agent (e.g., ["get_planner_info", "add_place_to_day"])', null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Agent execution time in milliseconds', null=True)),
                ('request_type', models.CharField(blank=True, help_text='Request type (e.g., "add_place", "search", "recommend")', max_length=50, null=True)),
                ('success', models.BooleanField(default=True, help_text='Whether the request was successfully processed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_idx', models.ForeignKey(db_column='room_idx', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='chat.chatroom')),
                ('trip_idx', models.ForeignKey(db_column='trip_idx', help_text='Associated trip for quick filtering', on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='plans.tripplan')),
                ('user_idx', models.ForeignKey(blank=True, db_column='user_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Request',
                'verbose_name_plural': 'Chat Requests',
                'db_table': 'chat_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_idx', '-created_at'], name='chat_reques_room_id_661aac_idx'), models.Index(fields=['user_idx', '-created_at'], name='chat_reques_user_id_fd4d3b_idx'), models.Index(fields=['trip_idx', '-created_at'], name='chat_reques_trip_id_68a384_idx'), models.Index(fields=['request_type'], name='chat_reques_request_f7a4d7_idx'), models.Index(fields=['success'], name='chat_reques_success_641868_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(check=models.Q(('msg_type__in', ['text', 'system', 'card', 'recommendation'])), name='chat_messages_msg_type_check'),
        ),
    ]
