# Generated by Django 4.2.9 on 2025-10-14 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_idx', models.AutoField(db_column='room_idx', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_idx', models.ForeignKey(db_column='trip_idx', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='plans.tripplan')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'chat_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_idx', models.AutoField(db_column='message_idx', primary_key=True, serialize=False)),
                ('msg_type', models.TextField(choices=[('text', 'Text'), ('system', 'System'), ('card', 'Card'), ('recommendation', 'Recommendation')], default='text')),
                ('content', models.TextField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_idx', models.ForeignKey(db_column='room_idx', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('user_idx', models.ForeignKey(blank=True, db_column='user_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(check=models.Q(('msg_type__in', ['text', 'system', 'card', 'recommendation'])), name='chat_messages_msg_type_check'),
        ),
    ]
