# Generated by Django 4.2.9 on 2025-11-17 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('query', models.TextField(help_text='검색 쿼리')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('province_idx', models.IntegerField(blank=True, null=True)),
                ('top_k', models.IntegerField(default=3)),
                ('search_time', models.FloatField(help_text='벡터 검색 시간 (초)')),
                ('llm_refinement_time', models.FloatField(blank=True, help_text='LLM 정제 시간 (초)', null=True)),
                ('total_time', models.FloatField(help_text='전체 시간 (초)')),
                ('results_count', models.IntegerField(help_text='검색된 결과 수')),
                ('rag_results', models.JSONField(blank=True, help_text='RAG 검색 결과', null=True)),
                ('refined_plan', models.JSONField(blank=True, help_text='LLM 정제 결과', null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rag_test_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='rag_test_lo_created_1424cd_idx'), models.Index(fields=['success'], name='rag_test_lo_success_530d0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('room_idx', models.IntegerField(blank=True, null=True)),
                ('user_message', models.TextField(help_text='사용자 입력')),
                ('detected_intent', models.CharField(blank=True, help_text='감지된 의도', max_length=100, null=True)),
                ('tool_used', models.CharField(blank=True, help_text='사용된 도구명', max_length=100, null=True)),
                ('total_time', models.FloatField(help_text='전체 처리 시간 (초)')),
                ('llm_time', models.FloatField(blank=True, help_text='LLM 응답 시간 (초)', null=True)),
                ('tool_time', models.FloatField(blank=True, help_text='Tool 실행 시간 (초)', null=True)),
                ('rag_time', models.FloatField(blank=True, help_text='RAG 검색 시간 (초)', null=True)),
                ('db_time', models.FloatField(blank=True, help_text='DB 쿼리 시간 (초)', null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_length', models.IntegerField(blank=True, help_text='응답 길이 (문자)', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='추가 성능 데이터', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_performance_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='bot_perform_created_3afc1d_idx'), models.Index(fields=['tool_used'], name='bot_perform_tool_us_555859_idx'), models.Index(fields=['success'], name='bot_perform_success_26d93c_idx')],
            },
        ),
    ]
