# Generated by Django 4.2.9 on 2025-11-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_ragtestlog_botperformancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragtestlog',
            name='avg_similarity_score',
            field=models.FloatField(blank=True, help_text='평균 유사도 점수', null=True),
        ),
        migrations.AddField(
            model_name='ragtestlog',
            name='max_similarity_score',
            field=models.FloatField(blank=True, help_text='최대 유사도 점수', null=True),
        ),
        migrations.AddField(
            model_name='ragtestlog',
            name='min_similarity_score',
            field=models.FloatField(blank=True, help_text='최소 유사도 점수', null=True),
        ),
        migrations.AddField(
            model_name='ragtestlog',
            name='similarity_std_dev',
            field=models.FloatField(blank=True, help_text='유사도 표준편차', null=True),
        ),
    ]
