# Generated by Django 4.2.9 on 2025-11-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('rate_idx', models.AutoField(db_column='rate_idx', primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=10)),
                ('bank', models.TextField()),
                ('buy', models.FloatField(blank=True, null=True)),
                ('sell', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates', to='common.country', to_field='country_code')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'exchange_rates',
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('currency_code', 'bank'), name='uq_exchange_rates_currency_bank'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency_code', 'bank')},
        ),
    ]
