# Generated by Django 4.2.9 on 2025-10-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMonthly',
            fields=[
                ('weather_monthly_idx', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('max_temp_c', models.DecimalField(blank=True, decimal_places=2, help_text='Average maximum temperature in Celsius', max_digits=5, null=True)),
                ('min_temp_c', models.DecimalField(blank=True, decimal_places=2, help_text='Average minimum temperature in Celsius', max_digits=5, null=True)),
                ('mean_temp_c', models.DecimalField(blank=True, decimal_places=2, help_text='Average mean temperature in Celsius', max_digits=5, null=True)),
                ('raindays', models.DecimalField(blank=True, decimal_places=2, help_text='Average number of rainy days', max_digits=5, null=True)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Average rainfall in millimeters', max_digits=7, null=True)),
                ('climate_from', models.DateField(blank=True, help_text='Climate data reference date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city_code', models.ForeignKey(blank=True, db_column='city_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_weather', to='common.region1', to_field='city_code')),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_weather', to='common.country', to_field='country_code')),
            ],
            options={
                'verbose_name': 'Monthly Weather',
                'verbose_name_plural': 'Monthly Weather',
                'db_table': 'weather_monthly',
                'ordering': ['month'],
                'indexes': [models.Index(fields=['month'], name='weather_mon_month_6ce436_idx'), models.Index(fields=['city_code', 'month'], name='weather_mon_city_co_5d6323_idx')],
                'unique_together': {('city_code', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WeatherDaily',
            fields=[
                ('weather_daily_idx', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('weather', models.TextField(blank=True, null=True)),
                ('temp_min_c', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum temperature in Celsius', max_digits=5, null=True)),
                ('temp_max_c', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum temperature in Celsius', max_digits=5, null=True)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Rainfall in millimeters', max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city_code', models.ForeignKey(blank=True, db_column='city_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_weather', to='common.region1', to_field='city_code')),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_weather', to='common.country', to_field='country_code')),
            ],
            options={
                'verbose_name': 'Daily Weather',
                'verbose_name_plural': 'Daily Weather',
                'db_table': 'weather_daily',
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['forecast_date'], name='weather_dai_forecas_7b7972_idx'), models.Index(fields=['city_code', 'forecast_date'], name='weather_dai_city_co_200718_idx')],
                'unique_together': {('city_code', 'forecast_date')},
            },
        ),
    ]
