# Generated by Django 4.2.9 on 2025-11-09 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdaily',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weatherdaily',
            name='city_idx',
            field=models.ForeignKey(blank=True, db_column='city_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_weather', to='common.city'),
        ),
        migrations.AddField(
            model_name='weatherdaily',
            name='district_idx',
            field=models.ForeignKey(blank=True, db_column='district_idx', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_weather', to='common.district'),
        ),
        migrations.AddField(
            model_name='weatherdaily',
            name='precipitation_am',
            field=models.IntegerField(blank=True, help_text='Morning precipitation probability (%)', null=True),
        ),
        migrations.AddField(
            model_name='weatherdaily',
            name='precipitation_pm',
            field=models.IntegerField(blank=True, help_text='Afternoon precipitation probability (%)', null=True),
        ),
        migrations.AddField(
            model_name='weatherdaily',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weatherdaily',
            name='weather_am',
            field=models.CharField(blank=True, help_text='Morning weather condition (맑음, 구름많음, 흐림, 비, 눈 등)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weatherdaily',
            name='weather_pm',
            field=models.CharField(blank=True, help_text='Afternoon weather condition', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdaily',
            name='temp_max_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum temperature in Celsius', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdaily',
            name='temp_min_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum temperature in Celsius', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdaily',
            name='weather',
            field=models.TextField(blank=True, help_text='Legacy field', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='weatherdaily',
            unique_together={('district_idx', 'forecast_date')},
        ),
        migrations.AddIndex(
            model_name='weatherdaily',
            index=models.Index(fields=['city_idx', 'forecast_date'], name='weather_dai_city_id_5229ef_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdaily',
            index=models.Index(fields=['district_idx', 'forecast_date'], name='weather_dai_distric_2a090b_idx'),
        ),
    ]
